### ISSUE TITLE
`julia-snail` fails 

### ISSUE THREAD

**Issue by orialb** [gcv/julia-snail#2]
Trying to run `julia-snail` fails when called for the first time with but works on the second time (if I kill the REPL + julia-process buffer it fails again). 
Here is the debug trace:
```
Debugger entered--Lisp error: (file-error "make client process failed" "Connection refused" :name "julia-process" :buffer #<buffer *julia* process> :host "localhost" :service 10011 :nowait nil :tls-parameters nil)
  make-network-process(:name "julia-process" :buffer #<buffer *julia* process> :host "localhost" :service 10011 :nowait nil :tls-parameters nil)
  open-network-stream("julia-process" #<buffer *julia* process> "localhost" 10011)
  julia-snail--repl-enable()
  julia-snail-repl-mode()
  julia-snail()
 ```

My system info: 
- Mac OS 10.14.6 (mojave)
- Emacs: 
```
GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, 
NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02
```
- Julia:
```
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```
- I am using Spacemacs (develop branch) but I don't think it has anything to do with this.

**Comment by gcv** [comment]
Could you please try this with your firewall disabled? Maybe disconnect your machine from the network first for safety.

**Comment by orialb** [comment]
this happens with the firewall disabled.

**Comment by orialb** [comment]
Not sure if it is relevant info, but if I first run `JuliaSnail.start()` in a separate terminal, `julia-snail` seems to work.

**Comment by gcv** [comment]
Interesting. Does the `JuliaSnail.start(...)` line appear in the Emacs-embedded REPL after you run `julia-snail`?

**Comment by orialb** [comment]
I think I solved this by increasing the wait time in: 
https://github.com/gcv/julia-snail/blob/33fe6d076509673226aab97a0136fc42b05fc6ca/julia-snail.el#L279

from 5000 to 50000. After this change it seems to be working.

**Comment by gcv** [comment]
Oh wow. Thanks! Can you try reverting the change I made earlier in https://github.com/gcv/julia-snail/commit/33fe6d076509673226aab97a0136fc42b05fc6ca and see if your increased timeout still works?

**Comment by orialb** [comment]
Sorry I referenced the wrong line in the comment above, I increased the timeout limit exactly in the same line you added in the latest commit, i.e I made the change in:
https://github.com/gcv/julia-snail/blob/33fe6d076509673226aab97a0136fc42b05fc6ca/julia-snail.el#L242

**Comment by gcv** [comment]
Got it, thanks. I just pushed https://github.com/gcv/julia-snail/commit/ed7a4bf35beb8d6692d2b60fe9e4acac6dc61dfa with bumped timeouts.

This is surprising, since you and I have exactly the same CPU and OS combination! Different Emacs builds though.

**Comment by orialb** [comment]
Great, I'll keep playing with this package :)

**Comment by tpapp** [comment]
I still have a problem with the first `julia-snail`: instead of erroring, it just keeps doing nothing and blocks the Emacs process (I get the hourglass). <kbd>C-g</kbd> interrupts it, and the second time it takes me to a Julia inferior process with 
```julia
julia> JuliaSnail.start(10011);
```
in the prompt.

Let me know if I should open a separate issue. I am using the latest `20200310.2223` from MELPA, Emacs 26.3, Ubuntu 20.04.

**Comment by orialb** [comment]
> I think I solved this by increasing the wait time 

Sorry, I made a stupid mistake, I think increasing the wait time didn't solve it for me as well. 

>Not sure if it is relevant info, but if I first run JuliaSnail.start() in a separate terminal, julia-snail seems to work.

Apparently the `JuliaSnail` server was still running in a separate terminal  (outside of emacs) all this time I was testing things although I thought I killed it.  :| 
Once I properly killed it I am back to the original problem, so maybe it is better to decrease back the timeout limit in order to not cause emacs to hang as the solution is probably somewhere else.

Sorry for leading you in the wrong direction.

**Comment by orialb** [comment]
I did a further check, I still think the problem is that the `open-network-stream` call somehow runs before the `JuliaSnail` server is up. I noted that the REPL buffer with the `JuliaSnail.start` command is already generated during the first call to `julia-snail`,  the second call doesn't try to connect to the server because `julia-snail--process` variable was already created in the first call.

If after the first call to `julia-snail`, I evaluate `(open-network-stream "julia-process" nil "localhost" julia-snail-port)` it seems to be able to connect (at least it doesn't error).

Maybe `julia-snail--wait-while` is not working as expected? I did an experiment replacing
https://github.com/gcv/julia-snail/blob/33fe6d076509673226aab97a0136fc42b05fc6ca/julia-snail.el#L242
with `(sleep-for 5)`, and in this case it seems to work.

**Comment by gcv** [comment]
Maybe the terminal behaves differently for you than it does for me. `julia-snail--wait-while` in the code snippet above looks at the terminal buffer and waits for the `julia>` prompt to appear, and treats that as a signal that the Snail server started properly. If the string `"julia>"` does not appear in the terminal (vterm) buffer and the cursor is not positioned after it, then yeah, nothing will work. It should look like this almost instantaneously:

<img width="513" alt="Screen Shot 2020-03-11 at 10 08 23" src="https://user-images.githubusercontent.com/10327/76444391-1d327b00-6381-11ea-97ee-0c9550c5b387.png">

The screenshot is of an Emacs vterm Julia Snail REPL window immediately after calling `julia-snail`. The prompt highlighted in red must be there. If there's a display problem, or if the cursor position does not match the screenshot, I'd like to know about it. That will point to a vterm problem. If it looks like this but the network connection fails, that would point to a different problem.

@tpapp, you wrote that the terminal hangs with `julia> JuliaSnail.start(10011);`. Does this mean that a subsequent `julia>` prompt does not appear?

**Comment by orialb** [comment]
This is what I get when using `(sleep-for 5)`:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/1208196/76445502-c8652380-63c5-11ea-8eea-86fc6876610f.png">

This is what I get with `julia-snail--wait-while` when I switch to the `*julia*` vterm buffer after it errors:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/1208196/76445690-1aa64480-63c6-11ea-83e8-e59c1bfd3553.png">

> if the string "julia>" does not appear in the terminal (vterm) buffer and the cursor is not positioned after it, then yeah, nothing will work. 

but in this case wouldn't `julia-snail--wait-while` just wait until the maxtime is reached and then try to connect to the server? 
If I put there `(julia-snail--wait-while (not (eq 0 1)) 20 5000)` it also works, so maybe the problem actually is that "julia>" appears before the server is up so it is not a good enough signal to wait for.

**Comment by tpapp** [comment]
Sorry if I was not precise. For me, the whole window is not popped up at all so I don't see anything. I can only get to it by switching buffers manually after `C-g`.

**Comment by orialb** [comment]
I guess that in my case the problem might be that point is located in the beginning of the line "julia> JuliaSnail.start(10010)" so the condition for `julia-snail--wait-while` evaluates to `nil` before the server is up. 

@tpapp  When you switch to the `vterm` buffer manually after the failed `julia-snail` call, where is point located?

**Comment by gcv** [comment]
@orialb: Interesting! That would explain it. Please try the following change:

In `JuliaSnail.jl`, find line 314 (in the `start` function, it's the one which says `global server_socket = Sockets.listen(port)`) and move it outside the outer `@async` block, so it becomes line 313. The first few lines of the `start` function should look like this:

```
function start(port=10011)
   global running = true
   global server_socket = Sockets.listen(port)
   @async begin
      while running
         client = Sockets.accept(server_socket)
         push!(client_sockets, client)
```

I actually don't think the delay is necessary waiting for the initial REPL, it's supposed to be synchronous. If this fixes the problem, try removing the delay, i.e., these lines:

```
          ;; XXX: This shouldn't be necessary with :async nil in the
          ;; send-to-repl call above, but maybe it returns too quickly anyway.
          (julia-snail--wait-while (not (string-equal "julia>" (current-word))) 20 50000)
```

**Comment by orialb** [comment]
Unfortunately it doesn't seem to fix the problem for me.
Maybe there is another way to test whether the server is up?
I think maybe the reason why point remains in the beginning of the line in my case is that 
```
   (julia-snail--send-to-repl (format "JuliaSnail.start(%d);" julia-snail-port)
          :repl-buf repl-buf
          :async nil)
```
runs before Julia finishes loading in the vterm buffer (as you can see from the screenshots above).

At the moment a simple workaround for me is to use:
```
(julia-snail--wait-while (not (string-equal "julia>" (current-word))) 20 5000)
(sleep-for 0.5)
```

**Comment by gcv** [comment]
Let's try using `julia-snail--wait-while` to look for the prompt before trying to start the server. See https://github.com/gcv/julia-snail/commit/e3a7bd1724145db63689f018b51ef8e5614467b2, specifically https://github.com/gcv/julia-snail/blob/e3a7bd1/julia-snail.el#L241-L246

**Comment by orialb** [comment]
hmm, seems to still not work, but now point is located at the correct position when I look at the vterm buffer after the failed call:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/1208196/76504523-2d615d80-6448-11ea-9977-66f5d466b506.png">

So I guess the problem is not what I thought.
Is there a way to try connecting and if it fails wait for some time and then try connecting again or something like this?

**Comment by gcv** [comment]
Pushed a change which tries to wait for things to be available, on both Julia and Emacs sides. It should now be in MELPA. Please let me know how that works.

**Comment by orialb** [comment]
It seems to be working now! Thanks for investing time in solving this.

Side question (will open a new issue if this is not the expected behavior): after the REPL loads the window looks like this
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/1208196/76576568-bd43ed80-64c2-11ea-930b-6b1717d3e6c6.png">

i.e. the buffer with the Julia file from which I called `julia-snail` is replaced with the `julia-process` buffer. I'm assuming this is this not the expected behavior?

**Comment by gcv** [comment]
Thanks for your patience in helping in track this down.

With regard to the process buffer replacing your source buffer: definitely not intended! Please open another ticket and include your `display-buffer-alist`.

**Comment by tpapp** [comment]
The issue is resolved for me too. Thanks!
